### ISSUE TITLE
FIX dates for development, presentation and so on FIX dashed bars in PP gant

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#107]

**Comment by carduz** [comment]
**FIX dashed bars**

**Comment by carduz** [comment]
**FIX dates, consider the 50% in the development**

**Comment by tux-mind** [comment]
![nothing to do here](http://i0.kym-cdn.com/photos/images/newsfeed/000/201/508/221435NothingtodoHereGifMadethiscuzIwas2479d82822723.gif?1321553488)
