### ISSUE TITLE
G1: Allow taxi drivers to sign up into the system.

### ISSUE THREAD

**Issue by tux-mind** [sweng2/sweng2#14]
Taxi drivers are like the staff, we should not provide a way to create such accounts from the outside, it should be created by an user with higher privileges.

**Comment by carduz** [comment]
we use the old system. The registration and deletion is managed by taxi company. I think that I have written all on assumption and domain. But it's a better idea if you check

**Comment by tux-mind** [comment]
so, isn't a goal of the new system, is just an already working feature, isn't it?

long story short: whocares :grin:

**Comment by carduz** [comment]
In our implementation the registration is managed by old system, so we
don't use to develop or describe it
