### ISSUE TITLE
Reliability requirement s

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#2]
I think that this can be a good section, but I don't know where we can put it? If I remember correctly it is a "non functional requirements"

**Comment by carduz** [comment]
@tux-mind @gdejaege

**Comment by gdejaege** [comment]
non functionnal requirement seems the most logic

**Comment by carduz** [comment]
yes, but.... do we need it?

**Comment by gdejaege** [comment]
hmm I don't know

**Comment by carduz** [comment]
@tux-mind what do you think?

**Comment by tux-mind** [comment]
at lesson the teacher spent more than an hour talking about reliability and availability.
I think that this it's an important point but we should make it well if we decide to do it.

but only 2 hours left for the deadline, I think that it's better to give it up.

**Comment by carduz** [comment]
I think we have to insert this in Design and architecture document

**Comment by tux-mind** [comment]
ok, closing.
