### ISSUE TITLE
Do we have to insert a descriotion for each mockup?

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#36]

**Comment by gdejaege** [comment]
I don't think

**Comment by carduz** [comment]
@tux-mind what do you think?

**Comment by tux-mind** [comment]
it's a mockup, just a title with "mobile application driver/client" and "web application" it's fine for me.

it is important to preserve the view order... lemme fix them

**Comment by carduz** [comment]
ok but we should insert this title in PDF
