### ISSUE TITLE
Name and phone number on moble app mockup

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#37]

**Comment by tux-mind** [comment]
phone number it's taken by the app ( `Permissions.READ_PHONE_STATE` ).
the name it's asked on the first run and can be changed in settings, should I made a mockup for this view ?

**Comment by carduz** [comment]
Only on android.... but unfortunately iOS is still alive  :(

**Comment by carduz** [comment]
@tux-mind look here

**Comment by gdejaege** [comment]
I think the mockups are there to give an Idea, they should not recover every single possible screen. If we only have mockups for an android app it is not a big deal

**Comment by carduz** [comment]
ok but we have to say " Permissions.READ_PHONE_STATE"

**Comment by carduz** [comment]
fixed
