### ISSUE TITLE
Consider taxi passengers limit when a request for more than 4 passengers is done

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#39]

**Comment by tux-mind** [comment]
??

do you mean that we shall specify the following workflow ?
- pick a request
- reserve taxis such that `sum[taxis.seats] >= request.passengers`
- create a `Ride` with those Taxis

if yes, where to wrote it ?

**Comment by carduz** [comment]
the answer is yes, but I have no idea where write this
