### ISSUE TITLE
Registered users

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#4]
We have to register users to store their preferences?
![schermata del 2015-10-25 16 50 46](https://cloud.githubusercontent.com/assets/10631614/10716413/930678d0-7b38-11e5-839a-bd4788d0e371.png)

**Comment by tux-mind** [comment]
[no no no](https://en.wikipedia.org/wiki/KISS_principle)

**Comment by carduz** [comment]
so... what do we do?

**Comment by gdejaege** [comment]
When a client make a reservation, an temporary client is stored in the system then once the ride is done we delete the client. No need for registration I think

**Comment by carduz** [comment]
I think that according to the text we should store informations about destination with sharing option and we shouldn't insert the sharing option mode. I think the text wants the sharing option always for destination indicated and never in other cases. But in my opinion this is useless and we have no time to do that, so I'll put our way as assumption

What do you think?

**Comment by carduz** [comment]
I have written this as assumption
