### ISSUE TITLE
Do we say the queue position in taxi notification? and in user notifciation?

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#41]

**Comment by tux-mind** [comment]
no IMHO.

I think that client don't need to known enqueued position of the taxi ( it is no more enqueued as it has been assigned to a ride ) and either the taxi does not need to known the enqueued position of a request.

**Comment by carduz** [comment]
But taxi has to know his position and even client has to know his position. Right?

**Comment by gdejaege** [comment]
taxi have to kow there position, users I think it's better for them if they know but it is not necessary.

**Comment by carduz** [comment]
If the answer is no we have to remove this from each part of the document

**Comment by tux-mind** [comment]
as @gdejaege said, taxi must known their position in the Zone Queue, but it has nothing to do with the notification.

as you can see from the mobile mockup.

![taxi driver main](https://github.com/sweng2/sweng2/raw/master/RASD/resources/mockup/mobile/mainactivity_taxidriver.png)

**Comment by carduz** [comment]
@gdejaege you should remove this from scenario, if you haven't done that yet

**Comment by gdejaege** [comment]
I think the scenarios are coherent with what we are saying but to be clear our conclusion is : Taxi drivers know their position in the queue (see mockup) and user do not know the position in the queue of their request.
[correct me if I'm wrong ;) ]

**Comment by carduz** [comment]
right.... @tux-mind the problem is:  we have few time

**Comment by tux-mind** [comment]
no, the problem is: I didn't understand what is the problem.

**Comment by carduz** [comment]
in the scenarios we have said that we send queu position as notification to clients

**Comment by tux-mind** [comment]
remove it. we send the taxi code, an ETA and the price (if available).

**Comment by carduz** [comment]
can you do that? (in scenarios)

**Comment by tux-mind** [comment]
cannot find it...

**Comment by carduz** [comment]
perfect, I think @gdejaege has updated it (good job ;)). In fact we have queue position only for drivers
