### ISSUE TITLE
shared ride fee computation

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#43]

**Comment by tux-mind** [comment]
> If others are willing to start a shared ride from the same zone going in the same direction, then the system arranges the route for the taxi driver, defines the fee for all persons sharing the taxi and informs the passengers and the taxi driver.
> -- _Assignments 1 and 2 (RASD and DD).pdf: part 3_

so it isn't a task made by the taxi driver.

**Comment by carduz** [comment]
So do we have to specify how calculate fees?

**Comment by tux-mind** [comment]
as the teacher said:

> we are in the world of _what_ not _how_

so I think that we should only write down that it's computed by the system, not how.

the problem is if we need to put that price into the Ride class.... I think that this is an urgent lack to fix.

**Comment by carduz** [comment]
I think we can write this as assumptions

**Comment by tux-mind** [comment]
yep, but we should also say who compute it.
It should be calculated by the server because the price it's something that it's sent to both `Driver` and `Client`.
I'm going to put it into the class diagram.

**Comment by carduz** [comment]
perfect ;)

**Comment by carduz** [comment]
done
