### ISSUE TITLE
Verify phone number

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#52]

**Comment by carduz** [comment]
we can say that we use an external service via API

**Comment by tux-mind** [comment]
mmmm, this is a good point.

we should verify a phone number before using it in our application.
so we have to add an input in out web mockup where a sent code is required to go further.

**Comment by carduz** [comment]
I think that we can add this as future improvement, since we have to change too things, what do you think? @tux-mind @gdejaege

**Comment by gdejaege** [comment]
when a client make a request some information have to be verified like the depart place etc ... I always tought the phone number was also verified

**Comment by carduz** [comment]
it's not verified, because to verify it we have to send an SMS to the client and he has to insert the code into the site/app. Buit to do that we have to change diagrams, mockup. In my opinion for the real situation this is a useless thing because the client has to do another step to reserve taxi each time.

So we can write that we don't verify the phone number because is a long step form the client side, since we want to promote a faster service

**Comment by gdejaege** [comment]
ok

**Comment by tux-mind** [comment]
not really.

in the web app ( the only one that need to verify the number ), we asks for the phone number in the first step.
we should require that code in the second step, beside the location and the optional scheduled time.

I think that it can be a bad value for the project, we have to fix it. the other way is to assume that the world is perfect and every submitted phone number is valid.

**Comment by carduz** [comment]
I think that if we change this we have to change too things and we can make too mistakes

**Comment by carduz** [comment]
If we add this we have to change for example the motivation of "not register user" since we said that a good motivation is the quick process to reserve a taxi, but if we add this step we have a long process

**Comment by carduz** [comment]
done in a bad way ;)
