### ISSUE TITLE
Squares

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#6]
Do we have to escape squares in markdown?

**Comment by tux-mind** [comment]
by square do you mean `[` and `]` ?

Square brackets are interpreted as something else only if you write them in a specific fashion.

like `[name](http://example.com/)` or `[name][1]` for links.

as you can see [this funny words] are displayed between square brackets, unless a link [title](http://google.com) match the name inside the brackets.

> NOTE: click on the :pencil2: icon in the top-right of this comment to see markdown source of this snippet.

closing, feel free to reopen if you have more questions :blush:
