### ISSUE TITLE
Take a look to bold statement in DD

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#61]

**Comment by carduz** [comment]
@tux-mind @gdejaege

**Comment by tux-mind** [comment]
### Link seq inserted on RASD OR NOT?

pdf will not have links ( across files I mean ), so it cannot be done.

### Make or not slides example diagram

when we have to expose the presentation ? in the classroom right ?

### Check diagrams if they are correct in our previously assumptions

WIP

### To end the ride we use the position of the driver, when the position it's nearby the final location the ride will be canceled.

I think that @gdejaege got a brilliant idea!

> do we really need to finish the ride ?

damn, it's perfect!
who cares about the state of the ride, leave it run, the `Driver` will switch it's availability back to `on` when he finishes the `Ride`.

compliments @gdejaege :blush: 

### WRITE SOMETHING?

lorem ipsum dolor

### Describe queue and availability algorithm MAKE OR NOT?

I think that the "availability" isn't an algorithm.
the algorithm is the request management, which takes into account the `Driver` state ( available or not ) but the availability "management" it's only a state of the `Driver` object.
for the `Queue` we can assume that add/remove operation of a `Queue` are quite standard just give a link to the Java 7 API docs.

**Comment by carduz** [comment]
done
