### ISSUE TITLE
fix 3.1 link in DD

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#69]

**Comment by gdejaege** [comment]
I am not sure wat it means but I added  numbering of the 3.1 and 3.2 sections (ex:  '##make ride and ...' becomes : '##3.2.make ride and ...')"

**Comment by carduz** [comment]
If I remember correctly  in that section there is a link (I don't remember if it is internal or not) to fix

**Comment by tux-mind** [comment]
I see no links.

![nothing to do here](http://i0.kym-cdn.com/photos/images/newsfeed/000/201/508/221435NothingtodoHereGifMadethiscuzIwas2479d82822723.gif?1321553488)

**Comment by carduz** [comment]
maybe it was already fixed
