### ISSUE TITLE
Do we have to insert the world and the machine?

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#7]

**Comment by gdejaege** [comment]
Yes, I think we have to do it, the assistant insisted on it during the lab session

**Comment by carduz** [comment]
@gdejaege @tux-mind who makes this?

**Comment by tux-mind** [comment]
I can try to do it tomorrow.
just remember this to me please ( using telegram, I have tents of notifications on GH ).

thaaaaaanks :blush:

**Comment by carduz** [comment]
this task has low priority

**Comment by carduz** [comment]
no :)
