### ISSUE TITLE
Have we written that the taxi app send continuosly the position?

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#74]

**Comment by gdejaege** [comment]
I do not remember having seen it

**Comment by tux-mind** [comment]
### RASD - description of the give problem

> On the other side the mobile app allows taxi drivers to accept or reject a ride request and to communicate automatically their position (so the zone).

### RASD - Functional requirments

> [G2] The system must be able to detect the taxi's location according to the taxi's GPS

### DD - 1.2 Scope

> On the other side the mobile app also allows taxi drivers to accept or reject a ride request and to communicate automatically their position (and therefore the zone where their are located).

### DD - 2.2 High level components and their interaction

> The taxi drivers can also send his position to the central. This can be done asynchronously. Taxi drivers also have to communicate with synchronous message with the central to log in.
