### ISSUE TITLE
Queue end

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#8]
What do we have to do if the queue ends? if all taxi reject the drive?

we can write as domain that this cannot happen

**Comment by gdejaege** [comment]
I think we should notify the user (that what I have put in functionnal requirements) It could happen that no taxi is willing to dothe ride (for exemple if a customer wants to go to far or whatever)

**Comment by carduz** [comment]
@gdejaege have you written this as requirement?

**Comment by gdejaege** [comment]
I made it but I deleted it because I'm not sure how we could handle this with merged request etc...

**Comment by carduz** [comment]
this is a good question... @tux-mind

**Comment by tux-mind** [comment]
if no one can satisfy your request ( just pick a zone with no taxis ) you'll receive a notification by SMS.

As for `SharedRequest`, `SingleRequest` should have a timeout in which we can wait for incoming taxis.
if no one arrives in the start zone in that time a notification is sent to the client and the request is deleted.

it's just my opinion, feel free to suggest another approach.

**Comment by carduz** [comment]
it's ok for me, I think that we don't need to change anything

**Comment by carduz** [comment]
I think that we have done.... please reopen if it's needed
