### ISSUE TITLE
write task list into the final document?

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#83]

**Comment by gdejaege** [comment]
During the class where we spoke about this document the teacher said it would be easier to make a section per method, and for each method expose the different bugs

**Comment by carduz** [comment]
but a lot of checks are referred to the entire class

**Comment by tux-mind** [comment]
@gdejaege we can use this approach for those inspections performed only on our methods, but many checks has been made on the whole class.

As far I can remember the following are the checks I made only on our methods:

35, 44, 45, 46, 49

I suggest to group our bugs by scope, as in the checklist ( and the [buglist](https://github.com/sweng2/sweng2/blob/master/CI/code/buglist.md) document ).

**Comment by gdejaege** [comment]
yes you are right, since we have a lot of checks for the whole document, it is a lot easier and clearer like this ;)
