### ISSUE TITLE
merging of purpose and scope

### ISSUE THREAD

**Issue by gdejaege** [sweng2/sweng2#84]
For me, the difference between the meaning of purpose and scope is not so clear. I think maybe they should go together and we should merge these sections.

what do you think ?

**Comment by carduz** [comment]
I have followed the official structure of the dd

**Comment by gdejaege** [comment]
So you want to keep it like this ?
In the DD I see the interest of keeping the two appart, here I think they go together well. But they also can be kept appart if you prefer it doesn't change a lot ;)

**Comment by carduz** [comment]
I think that in the first part we should describe what we have to do, while in the second one what is glashfish like in the previous document we said what is our application
