### ISSUE TITLE
change components view in DD

### ISSUE THREAD

**Issue by carduz** [sweng2/sweng2#93]

**Comment by tux-mind** [comment]
fixed

**Comment by carduz** [comment]
really? have you used the new version? the name is different, it is called revisioned

**Comment by tux-mind** [comment]
I thought that this issue was related to the component description, please give a more verbose description of the problem if you can :wink:

**Comment by carduz** [comment]
it should be referred to the image, please check if the image of the pdf are the last versions

**Comment by tux-mind** [comment]
[the pdf](https://github.com/sweng2/sweng2/blob/master/DD/DD.pdf) looks updated, closing.
